# Generated by Django 2.0.2 on 2018-06-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, null=True)),
                ('first_name', models.CharField(max_length=1000, null=True)),
                ('last_name', models.CharField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('purchase_status', models.CharField(choices=[('new', 'New'), ('canceled', 'Cancelled')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True, null=True)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('time', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_atlantic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_atlantic.Upload'),
        ),
        migrations.AddField(
            model_name='customer',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_atlantic.Upload'),
        ),
    ]
